N = 28
sentences = list(range(N))
dep = list(range(N))
tokens = list(range(N))
sentences[0] = 'clean the kitchen'
dep[0] = [('ROOT', 0, 1), ('det', 3, 2), ('dobj', 1, 3)]
tokens[0] = ['clean', 'the', 'kitchen']
sentences[1] = 'clean the kitchen quickly and the living room at 17 every monday'
dep[1] = [('ROOT', 0, 3), ('amod', 3, 1), ('det', 3, 2), ('advmod', 3, 4), ('cc', 3, 5), ('det', 8, 6), ('compound', 8, 7), ('conj', 3, 8), ('case', 10, 9), ('nmod', 8, 10), ('det', 12, 11), ('dep', 3, 12)]
tokens[1] = ['clean', 'the', 'kitchen', 'quickly', 'and', 'the', 'living', 'room', 'at', '17', 'every', 'monday']
sentences[2] = 'clean the kitchen at 10 every monday'
dep[2] = [('ROOT', 0, 3), ('amod', 3, 1), ('det', 3, 2), ('case', 5, 4), ('nmod', 3, 5), ('det', 7, 6), ('dep', 3, 7)]
tokens[2] = ['clean', 'the', 'kitchen', 'at', '10', 'every', 'monday']
sentences[3] = 'clean the bathroom today'
dep[3] = [('ROOT', 0, 3), ('amod', 3, 1), ('det', 3, 2), ('nmod:tmod', 3, 4)]
tokens[3] = ['clean', 'the', 'bathroom', 'today']
sentences[4] = 'today and tomorrow at 18'
dep[4] = [('ROOT', 0, 1), ('cc', 1, 2), ('conj', 1, 3), ('case', 5, 4), ('nmod', 1, 5)]
tokens[4] = ['today', 'and', 'tomorrow', 'at', '18']
sentences[5] = 'do all the cleaning today'
dep[5] = [('ROOT', 0, 1), ('det:predet', 4, 2), ('det', 4, 3), ('dobj', 1, 4), ('nmod:tmod', 1, 5)]
tokens[5] = ['do', 'all', 'the', 'cleaning', 'today']
sentences[6] = 'do it tomorrow'
dep[6] = [('ROOT', 0, 1), ('dobj', 1, 2), ('nmod:tmod', 1, 3)]
tokens[6] = ['do', 'it', 'tomorrow']
sentences[7] = 'clean quickly'
dep[7] = [('ROOT', 0, 1), ('advmod', 1, 2)]
tokens[7] = ['clean', 'quickly']
sentences[8] = 'do it fast'
dep[8] = [('ROOT', 0, 1), ('dobj', 1, 2), ('advmod', 1, 3)]
tokens[8] = ['do', 'it', 'fast']
sentences[9] = 'clean the kitchen quick'
dep[9] = [('ROOT', 0, 3), ('amod', 3, 1), ('det', 3, 2), ('amod', 3, 4)]
tokens[9] = ['clean', 'the', 'kitchen', 'quick']
sentences[10] = 'clean the kitchen quickly'
dep[10] = [('ROOT', 0, 3), ('amod', 3, 1), ('det', 3, 2), ('advmod', 3, 4)]
tokens[10] = ['clean', 'the', 'kitchen', 'quickly']
sentences[11] = 'in-depth cleaning'
dep[11] = [('ROOT', 0, 2), ('amod', 2, 1)]
tokens[11] = ['in-depth', 'cleaning']
sentences[12] = 'deep cleaning'
dep[12] = [('ROOT', 0, 2), ('amod', 2, 1)]
tokens[12] = ['deep', 'cleaning']
sentences[13] = 'quick'
dep[13] = [('ROOT', 0, 1)]
tokens[13] = ['quick']
sentences[14] = 'fast'
dep[14] = [('ROOT', 0, 1)]
tokens[14] = ['fast']
sentences[15] = 'in-depth'
dep[15] = [('ROOT', 0, 1)]
tokens[15] = ['in-depth']
sentences[16] = 'yes'
dep[16] = [('ROOT', 0, 1)]
tokens[16] = ['yes']
sentences[17] = 'no'
dep[17] = [('ROOT', 0, 1)]
tokens[17] = ['no']
sentences[18] = 'do it every day'
dep[18] = [('ROOT', 0, 1), ('dobj', 1, 2), ('det', 4, 3), ('nmod:tmod', 1, 4)]
tokens[18] = ['do', 'it', 'every', 'day']
sentences[19] = 'clean each day'
dep[19] = [('ROOT', 0, 1), ('det', 3, 2), ('nmod:tmod', 1, 3)]
tokens[19] = ['clean', 'each', 'day']
sentences[20] = 'every day'
dep[20] = [('ROOT', 0, 2), ('det', 2, 1)]
tokens[20] = ['every', 'day']
sentences[21] = 'each monday'
dep[21] = [('ROOT', 0, 2), ('det', 2, 1)]
tokens[21] = ['each', 'monday']
sentences[22] = 'every tuesday'
dep[22] = [('ROOT', 0, 2), ('det', 2, 1)]
tokens[22] = ['every', 'tuesday']
sentences[23] = 'monday and friday and not saturday'
dep[23] = [('ROOT', 0, 1), ('cc', 1, 2), ('conj', 1, 3), ('cc', 1, 4), ('neg', 6, 5), ('conj', 1, 6)]
tokens[23] = ['monday', 'and', 'friday', 'and', 'not', 'saturday']
sentences[24] = 'every day but not saturday and not sundayevery sunday and saturday'
dep[24] = [('ROOT', 0, 2), ('det', 2, 1), ('cc', 4, 3), ('cc', 2, 4), ('conj', 2, 5), ('cc', 5, 6), ('conj', 5, 7), ('compound', 9, 8), ('dep', 5, 9), ('cc', 9, 10), ('conj', 9, 11)]
tokens[24] = ['every', 'day', 'but', 'not', 'saturday', 'and', 'not', 'sundayevery', 'sunday', 'and', 'saturday']
sentences[25] = 'at 19'
dep[25] = [('ROOT', 0, 2), ('case', 2, 1)]
tokens[25] = ['at', '19']
sentences[26] = '12 hours'
dep[26] = [('ROOT', 0, 2), ('nummod', 2, 1)]
tokens[26] = ['12', 'hours']
sentences[27] = '6'
dep[27] = [('ROOT', 0, 1)]
tokens[27] = ['6']
